name: Synchronize Swedish
on: [push]
jobs:
  synchronize-swedish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Copy sv-SE into sv
        run: |
          cp -pr ./sv_SE/* ./sv
          sed -i'' -e 's/Language: sv_SE/Language: sv/g' ./sv/LC_MESSAGES/*.po
      - name: Commit changes
        run: |
          # Only try to commit if there are pending changes
          if [[ $(git diff --exit-code) || $(git ls-files --other --exclude-standard) ]]
          then
            git config user.email 'sumodev@mozilla.com'
            git config user.name 'github-action-sycnhronize-swedish'
            git add .
            git status
            git commit -m "copy sv-SE into sv"
            git push origin HEAD:master
          else
            echo "No changes found."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
